# Generated by Django 4.2.10 on 2024-02-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=18)),
                ('email', models.EmailField(default='google@com', max_length=254)),
                ('address', models.TextField(default='earth')),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
