# Generated by Django 4.2.10 on 2024-02-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(default='engineering', max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(default='google@goole.com', max_length=254),
        ),
    ]
