# Generated by Django 4.2.10 on 2024-02-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_user_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_register',
        ),
    ]
